services:
  producer-service:
    image: ${DOCKERHUB_USERNAME}/producer-service:${IMAGE_TAG:-latest}
    container_name: producer-service
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      SERVER_PORT: 8081
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      ISSUER_URI: ${ISSUER_URI}
      JWK_SET_URI: ${JWK_SET_URI}
      AUDIENCE: ${AUDIENCE}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
      SPRING_JPA_PROPERTIES_ORACLE_NET_TNS_ADMIN: /app/src/main/resources/Wallet_MBD
      SPRING_JPA_PROPERTIES_ORACLE_NET_WALLET_LOCATION: /app/src/main/resources/Wallet_MBD
    networks:
      - guia-network

  consumer-service:
    image: ${DOCKERHUB_USERNAME}/consumer-service:${IMAGE_TAG:-latest}
    container_name: consumer-service
    restart: unless-stopped
    ports:
      - "8082:8082"
    environment:
      SERVER_PORT: 8082
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
      SPRING_JPA_PROPERTIES_ORACLE_NET_TNS_ADMIN: /app/src/main/resources/Wallet_MBD
      SPRING_JPA_PROPERTIES_ORACLE_NET_WALLET_LOCATION: /app/src/main/resources/Wallet_MBD
    networks:
      - guia-network

networks:
  guia-network:
    external: true